### PR TITLE
continuation of #312

### PR DESCRIPTION
**Pull request by m7pr**
One commit was missing from https://github.com/insightsengineering/teal.data/pull/312

### CODE REVIEW

**Comment by m7pr** [comment]
Sorry #312  got merged during auto-merge strategy on when I accepted the suggestion lol
I continued with one more commit in here

**Review by kartikeyakirar — APPROVED** [review]

**Comment by kartikeyakirar** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by m7pr** [comment]
recheck

**Review by gogonzo — APPROVED** [review]
👍

**Pull request merged**
