### PR TITLE
[skip vbump] upversion to 0.4.0

### PR DESCRIPTION
**Pull request by donyunardi**
Related with #226

### CODE REVIEW

**Review by vedhav — APPROVED** [review]
🚀

**Comment by donyunardi** [comment]
teal.data now in cran:
https://cran.r-project.org/web/packages/teal.data/index.html

**Comment by vedhav** [comment]
I think we talked about reverting the examples commit after the cran release.

**Comment by donyunardi** [comment]
I don't see any examples commit being removed for teal.data. 
Do you see any?

**Comment by averissimo** [comment]
`teal.data` does not have these internal examples.

`teal.slice` does.

**Comment by vedhav** [comment]
Oh, thank god. I was unable to find them anywhere :D

**Pull request merged**
