### PR TITLE
Update DESCRIPTION

### PR DESCRIPTION
**Pull request by pawelru**
- Config/Needs/verdepcheck entries in new line
- add `bioc::` for packages from Bioconductor

### CODE REVIEW

**Review by averissimo — APPROVED** [review]
Thanks for catching this.

The `r.pkg.template/.github/workflows/version-bump.yaml` action will always refactor the `Config/Needs/verdepcheck` to single line though (with `NORMALIZE = TRUE` option).

**Comment by pawelru** [comment]
> The r.pkg.template/.github/workflows/version-bump.yaml action will always refactor the Config/Needs/verdepcheck to single line though (with NORMALIZE = TRUE option).

Good find! Can you please make a PR then?

**Comment by averissimo** [comment]
Sure can, but @pawelru this will have a side effect that packages within fields won't be sorted or whitespace being "normalized". That is a nice feature to have.

We correct the `desc_field` during the gh action after normalizing

```diff
diff --git a/.github/workflows/version-bump.yaml b/.github/workflows/version-bump.yaml
index 0d41874..a8941a1 100644
--- a/.github/workflows/version-bump.yaml
+++ b/.github/workflows/version-bump.yaml
@@ -63,7 +63,23 @@ jobs:
 
       - name: Bump version in DESCRIPTION 📜
         if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || inputs.vbump-after-release == true }}
-        run: desc::desc_bump_version("dev", normalize = TRUE)
+        run: |
+          desc::desc_bump_version("dev", normalize = TRUE)
+          # verdepcheck with 1 line per package
+          d <- desc::description$new("dev")
+          desc_field_name <- "Config/Needs/verdepcheck"
+          if (d$has_fields(field_name) && !identical(d$get_field(field_name), "")) {
+            desc_field_sep <- "\n    "
+            desc_field_normalized <- paste0(
+              field_sep,
+              paste(
+                strsplit(d$get_field(field_name), ", ")[[1]],
+                collapse = field_sep
+              )
+            )
+            d$set(field_name, desc_field_normalized)
+            d$write(file = "dev")
+          }
         shell: Rscript {0}
         working-directory: ${{ inputs.package-subdirectory }}
 

```

**Comment by pawelru** [comment]
Thanks for checking. That's quite a lot of custom code :/ Let's leave that then. 
Is this a worth raising within `desc` package? WDYT?

**Comment by averissimo** [comment]
I managed to reduce the code to fewer lines. There was already an issue being tracked on https://github.com/r-lib/desc/issues/122

```diff
diff --git a/.github/workflows/version-bump.yaml b/.github/workflows/version-bump.yaml
index 0d41874..f258d28 100644
--- a/.github/workflows/version-bump.yaml
+++ b/.github/workflows/version-bump.yaml
@@ -63,7 +63,14 @@ jobs:
 
       - name: Bump version in DESCRIPTION 📜
         if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || inputs.vbump-after-release == true }}
-        run: desc::desc_bump_version("dev", normalize = TRUE)
+        run: |
+          desc::desc_bump_version("dev", normalize = TRUE)
+          # verdepcheck splitting into new lines
+          d <- desc::description$new("dev")
+          desc_field_name <- "Config/Needs/verdepcheck"
+          if (desc$has_fields(desc_field_name)) {
+            desc$set_list(desc_field_name, desc$get_list(desc_field_name), sep = ",\n\t\t")
+          }
         shell: Rscript {0}
         working-directory: ${{ inputs.package-subdirectory }}
```

#### Example

``` r
tf <- tempfile()
text <- "Package: test\nImports: tdplyr, tibble\nConfig/Needs/website: tidyverse/tidytemplate, r-lib/desc"

desc <- desc::description$new(text = text)
desc$normalize()
desc_field_name <- "Config/Needs/website"
if (desc$has_fields(desc_field_name)) {
  desc$set_list(desc_field_name, desc$get_list(desc_field_name), sep = ",\n    ")
}
desc$write(file = tf)
readLines(tf) |> paste0(collapse = "\n") |> cat()
#> Package: test
#> Imports: 
#>     tdplyr,
#>     tibble
#> Config/Needs/website: tidyverse/tidytemplate,
#>     r-lib/desc
```

<sup>Created on 2023-10-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Pull request merged**
