### PR TITLE
Add a vignette for showcasing the teal_data changes

### LINKED ISSUE #174: Write a new vignette about `teal_data`
Since TealData is deprecated, we should no longer teach in the vignettes about this class. So we have (at least) two altnernative solutions:
- remove vignettes describing all (unwanted) ways of specifying data
- state in the old vignettes that their content is deprecated

There should be new vignettes:
- [x] `teal_data` class and it's methods and idea behind @gogonzo 
- [x] Reproducibility check
- [x] https://github.com/insightsengineering/teal.data/issues/202
- [x] using `teal_data` in teal application (this should be in `teal`)
- [x] how to migrate from `TealData` to `teal_data` and from `tdata` to `teal_data` @vedhav

### PR DESCRIPTION
**Pull request by vedhav**
Closes #174 

Preview the vignette at [https://vedhav.github.io/teal.data/articles/migrate-to-teal_data.html](https://vedhav.github.io/teal.data/articles/migrate-to-teal_data.html)

### CODE REVIEW

**Comment by pawelru** [comment]
I have just discussed this @gogonzo about where to put this migration guide - repo file, vignette, issue and GH discussion thread were the options. The latter two could support users feedback in form of comments that might be nice in the context of QA or potential issues. @gogonzo did we reach the alignment? Have you talked to @vedhav?

**Comment by vedhav** [comment]
Yeah, I'm not sure about the placement of this vignette as well. If I had to choose, I would like to place this vignette in the `teal` repo as it will reach more people. But, I thought we could link this over there in some relevant place.
Regardless, it's under `Delayed Data Loading` right now and we can certainly move it under a suitable new section and its link in the `NEWS.md`.

**Comment by gogonzo** [comment]
@vedhav please make a PR in `teal` we can discuss there where to put this vignette. Please avoid `package::` prefixing in the vignette but use `library(package)` instead.

**Comment by gogonzo** [comment]
I was thinking to include a table with simple calls replacement. To have a summary of the change on top of this document. Then in each section we can explain teal_data, cdisc_data and ddl

| former | new |
|---|---|
| teal_data(<br>  dataset("IRIS",  iris, code = "IRIS <- iris"),<br>  dataset("MTCARS", mtcars, code = "MTCARS <- mtcars")<br>) | teal_data(<br>  IRIS = iris,<br>  MTCARS = mtcars,<br>  code = quote({<br>    IRIS <- iris<br>    MTCARS <- mtcars<br>  }) |
| teal_data(<br>  cdisc_connector(...)<br>) | ddl(<br>  code = ...,<br>  ui = ...,<br>  server ...,<br>  join_keys = ...,<br>  datanames = ...<br>) |
| cdisc_data(<cdisc datasets>) | cdisc_data(<cdisc data frames>) |




I think PR could target `ddl@teal_data@main` branch. PR could be updated along with change of `ddl` design.

**Comment by vedhav** [comment]
Closing this in favor of [teal PR #944](https://github.com/insightsengineering/teal/pull/944)

**Pull request closed without merging**
