### PR TITLE
265 fix issue for using code in `quote` function with `get_code`

### LINKED ISSUE #265: error when getting code that contains language objects
```
> data <- teal_data() |> eval_code(
+   code = '
+     expr <- quote(x <- x + 1)
+     x <- 0
+     eval(expr)
+   '
+ )
> get_code(data, datanames = NULL) %>% cat

    expr <- quote(x <- x + 1)
    x <- 0
    eval(expr)
  > get_code(data, datanames = "x") %>% cat
Error in if (x$text[ass_cond] == "->") { : the condition has length > 1
```

### PR DESCRIPTION
**Pull request by m7pr**
Close #265

### CODE REVIEW

**Review by chlebowa — APPROVED** [review]
:+1:

**Comment by chlebowa** [comment]
Upon closer inspection, this may be a little overzealous.
```
> data <- teal_data() |> eval_code(
+   code = '
+   expr <- quote(x <- x + 1)
+   x <- 0
+ '
+ )
> get_code(data, datanames = "x") %>% cat
expr <- quote(x <- x + 1)
x <- 0
```

`expr` will not be evaluated so it should not be included.

**Comment by m7pr** [comment]
should I revert?

**Comment by chlebowa** [comment]
I'm not sure. We know that an expression is created. Is it possible to check whether it is evaluated later on?

**Pull request merged**
