### PR TITLE
233 detect assign in code with `get_code_dependency`

### LINKED ISSUE #233: extend code parser detection to handle `assign` function
Currently in such code

```r
  code <- c(
    "a <- 1",
    "assign('b', 5)",
    "assign(value = 7, x = 'c')",
    "b <- b + 2",
    "c <- b"
  )
```

`get_code_dependency` would not extract `assign` functions for objects `b` and `c`.

The needs is to be able to handle `assign` function so those lines are also extracted as part of the code creation of objects `c` and `b`

### PR DESCRIPTION
**Pull request by m7pr**
**Merge after** https://github.com/insightsengineering/teal.data/pull/230
Closes #233 

Added one more test for future improvement, where we are not able to handle `x` parameter passed to `assign` function as `variable`.

Such specs for `assign` are handled

```r
  code <- c(
    "a <- 1",
    "assign('b', 5)",
    "assign(value = 7, x = 'c')",
    "b <- b + 2",
    "c <- b"
  )
```

and below is not (yet!)

```r
  code <- c(
    "z <- 'a'",
    "assign(x = z, 5)",
    "b <- a"
  )
```

### CODE REVIEW

**Comment by kartikeyakirar** [comment]
@m7pr  It appears that when using only  `assign `function without specifying variable in the code, an error is encountered. 

```
code <- c("assign(adae, teal.data::rADAE)", "assign(adsl, teal.data::rADSL)")
tdata <- eval_code(teal_data(), code)
datanames(tdata) <- c("adsl", "adae")
get_code(tdata, datanames = "adae")

# Error: object 'adae' not found
# when evaluating qenv code:
#   assign(adae, teal.data::rADAE)
# 
# trace:
#   assign(adae, teal.data::rADAE)
# assign(adsl, teal.data::rADSL)

code <- c("adae <- teal.data::rADAE", "adsl <- teal.data::rADSL")
tdata <- eval_code(teal_data(), code)
datanames(tdata) <- c("adsl", "adae")
get_code(tdata, datanames = "adae")
#[1] "adae <- teal.data::rADAE"
```

**Comment by chlebowa** [comment]
image

**Comment by chlebowa** [comment]
But still
```
> code <- c("assign('adae', teal.data::rADAE)", "assign('adsl', teal.data::rADSL)")
> tdata <- eval_code(teal_data(), code)
> datanames(tdata) <- c("adsl", "adae")
> get_code(tdata, datanames = "adsl")
character(0)
Warning message:
In get_code_dependency(object@code, datanames) :
  Object(s) not found in code: adsl
```

**Comment by m7pr** [comment]
Yes @kartikeyakirar I did not yet cover the case where `x` is passed as a variable. Only when it is passed directly as a character. So this is not the part of this PR, however I have an idea on how to cover that in another PR.


@chlebowa in your case I think something is off in eval_code(). I tested functionality just on teal_data(code=code) where code was not evaluated and for the cases included in tests it did work. Will see what's going on with eval_code() for when we use assign(), but was focusing on parsing the character code

**Comment by kartikeyakirar** [comment]
> So this is not the part of this PR, however I have an idea on how to cover that in another PR.

Understood, Could you log the issue so we can keep track of it?

**Review by kartikeyakirar — APPROVED** [review]
👍

**Comment by m7pr** [comment]
Sorry guys, there was an auto merge in here. I opened 2 more issues to cover what we outlined here

https://github.com/insightsengineering/teal.data/issues/237
https://github.com/insightsengineering/teal.data/issues/238

**Comment by m7pr** [comment]
Just to let you know, this merged PR fixed some issues, but we found out few more

**Comment by chlebowa** [comment]
> @chlebowa in your case I think something is off in eval_code(). I tested functionality just on teal_data(code=code) where code was not evaluated and for the cases included in tests it did work. Will see what's going on with eval_code() for when we use assign(), but was focusing on parsing the character code

No, `@env` contents checked out.


> Just to let you know, this merged PR fixed some issues, but we found out few more

Perhaps the merge was premature?

**Comment by m7pr** [comment]
It was, as I enabled auto-merge 🤦 

Working on this one https://github.com/insightsengineering/teal.data/issues/237 currently

**Pull request merged**
