### PR TITLE
Append `testthat` prefix for `join_keys` tests

### PR DESCRIPTION
**Pull request by m7pr**
🥇

### CODE REVIEW

**Review by averissimo — APPROVED** [review]
Added a few that were missing. 

Seems good!

Q: Can you point me to documentation or issue where this convention of prefixing `test´that::` is defined?

**Review by chlebowa — APPROVED** [review]
:1st_place_medal:

**Comment by chlebowa** [comment]
> Q: Can you point me to documentation or issue where this convention of prefixing `test´that::` is defined?

I don't believe there is one but the conventions is: in tests, prefix everything not native to the package tested. This goes even for `shiny` in `Depends: shiny` packages such as `teal`,

**Comment by averissimo** [comment]
The `insightsengineering` packages are the first place I see this being applied for {testthat} expectations, `test_that()` and other {testthat} functions, hence the question.

My question was solely about {testthat} :-) shiny & others make obvious sense.

**Comment by chlebowa** [comment]
Like many NEST conventions, I wasn't here when they were adopted, so I merely pass them on :slightly_smiling_face:

**Comment by averissimo** [comment]
@pawelru care to give some context? :grin:

**Comment by pawelru** [comment]
hmmm can't recall tbh
either way it's ok - the most important thing is to stay consistent within a package

**Pull request merged**
