### PR TITLE
readme updates

### PR DESCRIPTION
**Pull request by m7pr**
Related to https://github.com/insightsengineering/coredev-tasks/issues/462

### CODE REVIEW

**Comment by kartikeyakirar** [comment]
Looks Good 👍

**Review by averissimo — CHANGES_REQUESTED** [review]
I can't comment on code as it wasn't changed, but on `vignettes/teal-data.Rmd` it is using the `.../main/...` on the `{teal}` URLs instead of the `latest-tag`

Do you mind if I commit to the branch?

```diff
diff --git a/vignettes/teal-data.Rmd b/vignettes/teal-data.Rmd
index 67cdb47..32429a7 100644
--- a/vignettes/teal-data.Rmd
+++ b/vignettes/teal-data.Rmd
@@ -43,9 +43,9 @@ my_general_data <- teal_data(
 
 The `teal.data` package provides many features to help specify your data:
 
-- [Specifying `ADaM` data](https://insightsengineering.github.io/teal/main/articles/including-adam-data-in-teal.html)
-- [Specifying `MultiAssayExperiment` data](https://insightsengineering.github.io/teal/main/articles/including-mae-data-in-teal.html)
-- [Specifying general relational data](https://insightsengineering.github.io/teal/main/articles/including-general-data-in-teal.html)
+- [Specifying `ADaM` data](https://insightsengineering.github.io/teal/latest-tag/articles/including-adam-data-in-teal.html)
+- [Specifying `MultiAssayExperiment` data](https://insightsengineering.github.io/teal/latest-tag/articles/including-mae-data-in-teal.html)
+- [Specifying general relational data](https://insightsengineering.github.io/teal/latest-tag/articles/including-general-data-in-teal.html)
 - [Specifying relationships between your datasets](join-keys.html)
 - [Dynamically loading your data (`DDL`)](using-delayed-data-basic.html)
 - [Pre-processing data](preprocessing-data.html)
```

**Comment by m7pr** [comment]
Thanks @averissimo, looks like something got shipped into the main branch and then merged here!

**Comment by m7pr** [comment]
Thanks for noticing! Fixed in here https://github.com/insightsengineering/teal.data/pull/166/commits/f35d738acae3d377d0ae776116d6111d56afb1d6

**Review by donyunardi — APPROVED** [review]
LGTM

**Review by donyunardi — CHANGES_REQUESTED** [review]
I ran the `urlchecker::url_check()` and got this message:
```r
✖ Error: man/col_labels.Rd:8:7 Error: CRAN URL not in canonical form
\href{https://cran.r-project.org/web/packages/formatters/index.html}{formatters} package, to reduce the complexity of

✖ Error: man/col_relabel.Rd:8:7 Error: CRAN URL not in canonical form
\href{https://cran.r-project.org/web/packages/formatters/index.html}{formatters} package, to reduce the complexity of

```

Should we update the formatters URL in the roxygen note for these two functions to:
```
\href{https://cran.r-project.org/package=formatters}{formatters}
```

**Review by averissimo — APPROVED** [review]
LGTM after addressing @donyunardi's comment about urls

**Comment by m7pr** [comment]
Thanks @donyunardi - really good finding! Thanks for double checking

**Comment by m7pr** [comment]
Feedback addresses, waiting for @donyunardi to re-review and accept!

**Review by donyunardi — APPROVED** [review]
LGTM!

**Pull request merged**
